# Generated by Django 5.0.7 on 2024-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('hospedajes', models.CharField(max_length=255)),
                ('transporte', models.CharField(max_length=255)),
                ('formas_llegar', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
    ]
